version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: nest-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest_postgress
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Optionally, you can mount custom initialization scripts
      # - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
    driver: local